server:
  port: 4005

spring:
  application:
    name: auth-service

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME:org.h2.Driver}
    hikari:
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: always
      platform: postgres
