version: "3.8"

services:
  app:
    container_name: patient-service
    image: patient-service:latest
    ports:
      - "4000:4000"
    environment:
      JAVA_TOOL_OPTIONS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_DATASOURCE_URL: jdbc:postgresql://patient-service-db:5432/patientdb
      SPRING_DATASOURCE_USERNAME: admin_user
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - internal
    depends_on:
      - patient-service-db

  patient-service-db:
    container_name: postgres
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: patientdb
    networks:
      - internal

networks:
  internal:
    driver: bridge

volumes:
  pgdata: