// Create a new patient
POST http://localhost:4100/api/patients
Content-Type: application/json

{
  "firstName": "Wayne",
  "lastName": "Rooney",
  "dob": "1991-01-15",
  "email": "wayne.rooneyForKafka5@email.com",
  "phoneNumber": "555-0101",
  "gender": "MALE",
  "address": {
    "street": "123 Main St",
    "city": "New York",
    "state": "NY",
    "zipCode": "10001",
    "country": "USA"
  },
  "insurance": {
    "provider": "Blue Cross",
    "policyNumber": "RRV2222244"
  }
}

HTTP/1.1 200  - OK
transfer-encoding: chunked
content-type: application/json
date: Wed, 16 Jul 2025 18:22:09 GMT
connection: close
###
