// Create a new patient
# @ ref json
PUT http://localhost:4100/api/patients/b25c9c60-ddf0-4be7-8058-74c31fd65e55
Authorization: Bearer {{json.token}}
Content-Type: application/json

{
  "firstName": "Waynew",
  "lastName": "Rooney1",
  "dob": "1991-01-15",
  "email": "john.doe333@email.com",
  "phoneNumber": "555-01011",
  "gender": "MALE",
  "address": {
    "street": "123 Main Street",
    "city": "New York",
    "state": "NY",
    "zipCode": "10001",
    "country": "USA"
  },
  "insurance": {
    "provider": "Blue Cross",
    "policyNumber": "RRV2222244"
  }
}

HTTP/1.1 200  - OK
transfer-encoding: chunked
content-type: application/json
date: Wed, 16 Jul 2025 18:23:11 GMT
connection: close