// Create a new patient
PUT http://localhost:4000/patients/95999862-1887-40e4-a010-43eabef29b59
Content-Type: application/json

{
  "firstName": "Waynew",
  "lastName": "Rooney1",
  "dob": "1991-01-15",
  "email": "john.doe333@email.com",
  "phoneNumber": "555-01011",
  "gender": "MALE",
  "address": {
    "street": "123 Main Street",
    "city": "New York",
    "state": "NY",
    "zipCode": "10001",
    "country": "USA"
  },
  "insurance": {
    "provider": "Blue Cross",
    "policyNumber": "RRV2222244"
  }
}

HTTP/1.1 200  - OK
content-type: application/json
transfer-encoding: chunked
date: Tue, 15 Jul 2025 20:02:31 GMT
connection: close