server:
  port: 4002

spring:
  application:
    name: analytics-service

  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: analytics-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
      auto-offset-reset: earliest
      enable-auto-commit: true
    listener:
      concurrency: 3
    admin:
      auto-create: true
      
