GET http://localhost:4005/validate
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbkBwbXMuY29tIiwicm9sZXMiOiJBRE1JTiIsImlhdCI6MTc1MzczMzY1OSwiZXhwIjoxNzUzNzM3MjU5fQ.0zRoMRSfULTm2x42APU0myOCD1MYvhf0R66WKAlcrow