# @ ref json
GET http://localhost:4005/validate
Authorization: Bearer {{json.token }}

HTTP/1.1 200  - OK
x-content-type-options: nosniff
x-xss-protection: 0
cache-control: no-cache, no-store, max-age=0, must-revalidate
pragma: no-cache
expires: 0
x-frame-options: SAMEORIGIN
content-type: application/json
transfer-encoding: chunked
date: Wed, 30 Jul 2025 14:07:39 GMT
connection: close